### The FQDN and port number where the server can be reached from the Internet.
public_address = "localhost:4433"

[provisioning]
### The full web address of the supervisor to contact and send reports to.
url = "http://localhost:7000/internal"

[quic]
### The socket where incoming QUIC connections are accepted from.
binding = "0.0.0.0:4433"
### The path to a PEM-encoded leaf certificate followed by optional intermediate certificates.
certificate_file = "fullchain.pem"
### The path to a PEM-encoded private key.
privatekey_file = "privkey.pem"

[http]
### The socket where incoming WebSocket connections are accepted from.
binding = "0.0.0.0:4433"
### The path to a PEM-encoded leaf certificate followed by optional intermediate certificates.
certificate_file = "fullchain.pem"
### The path to a PEM-encoded private key.
privatekey_file = "privkey.pem"
### Socket where WebRTC connections are accepted from.
webrtc_binding = "0.0.0.0:8844"
### The list of IP addresses to be offered as candidates.
webrtc_candidates = ["127.0.0.1", "::1"]

[log.terminal]
### The verbosity level [0-3] to define how much information should be written to logs (defaults to 1).
verbosity = 1
### Optional list of modules filtered from logs to prevent unnecessary noise, except for error messages.
filters = ["webrtc", "webrtc_ice"]

[metrics]
### Labels that are added to all reported metrics.
global_labels = { deployment = "foo" }
